takeout:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: takeout_take_out
    username: root
    password: ${SKY_DATASOURCE_PASSWORD:}
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: ${ALIOSS_ACCESS_KEY_ID:}
    access-key-secret: ${ALIOSS_ACCESS_KEY_SECRET:}
    bucket-name: java-ai-01-tsr
