server:
  port: 8080

spring:
  profiles:
    active: dev
  main:
    allow-circular-references: true
  datasource:
    druid:
      driver-class-name: ${takeout.datasource.driver-class-name}
      url: jdbc:mysql://${takeout.datasource.host}:${takeout.datasource.port}/${takeout.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: ${takeout.datasource.username}
      password: ${takeout.datasource.password}
  redis:
    host: ${takeout.redis.host}
    port: ${takeout.redis.port}
    password: ${takeout.redis.password}
    database: ${takeout.redis.database}


mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.takeout.entity
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true

logging:
  level:
    com:
      takeout:
        mapper: debug
        service: info
        controller: info

takeout:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    admin-secret-key: ${SKY_JWT_ADMIN_SECRET:}
    # 设置jwt过期时间
    admin-ttl: 7200000
    # 设置前端传递过来的令牌名称
    admin-token-name: token
    user-secret-key: ${SKY_JWT_USER_SECRET:}
    user-ttl: 7200000
    user-token-name: authentication


  alioss:
    endpoint: ${takeout.alioss.endpoint}
    access-key-id: ${takeout.alioss.access-key-id}
    access-key-secret: ${takeout.alioss.access-key-secret}
    bucket-name: ${takeout.alioss.bucket-name}

  wechat:
    appid: ${takeout.wechat.appid}
    secret: ${takeout.wechat.secret}

  shop:
    address: ${takeout.shop.address}
  baidu:
    ak: ${takeout.baidu.ak}
